language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - os: linux
      dist: xenial
      php: 7.1
      env: COMPOSER_VERSION=--1
    - os: linux
      dist: xenial
      php: 7.1
      env: COMPOSER_VERSION=--snapshot
    - os: linux
      dist: xenial
      php: 7.4
      env: COMPOSER_VERSION=--snapshot
    - os: osx
      osx_image: xcode12
      language: generic
      env: COMPOSER_VERSION=--1

before_script:
  - mkdir -p "$HOME/phar-bin"
  - curl -sSfL -o "$HOME/phar-bin/phpunit" https://phar.phpunit.de/phpunit-6.phar ; chmod 755 "$HOME/phar-bin/phpunit"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then php --version; brew install composer ; fi
  - "composer self-update $COMPOSER_VERSION"
  - "composer install --no-progress --no-interaction"

script:
  - "$HOME/phar-bin/phpunit"
